### ISSUE TITLE
Crash when opening notifications/DM Tab (Nightly)

### ISSUE THREAD

**Issue by bernd289** [tuskyapp/Tusky#1038]
```
02-12 21:47:52.754 17235 17719 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
02-12 21:47:52.754 17235 17719 E AndroidRuntime: Process: com.keylesspalace.tusky.test, PID: 17235
02-12 21:47:52.754 17235 17719 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.keylesspalace.tusky.entity.Status.getId()' on a null object reference
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at com.keylesspalace.tusky.c.a.d.a(SourceFile:1169)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at com.keylesspalace.tusky.c.a.i.a(SourceFile:1098)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at com.keylesspalace.tusky.c.a.i$f$a$1.run(SourceFile:48)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at androidx.k.f.a(SourceFile:298)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at com.keylesspalace.tusky.c.a.i$f$a.run(SourceFile:46)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-12 21:47:52.754 17235 17719 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

* * * *
- Tusky Version: 4.1-e371fa0
- Android Version: 9
- Android Device: Samsung Galaxy S9+
- Mastodon instance (if applicable): layer8.space

**Comment by charlag** [comment]
Oh,  thanks for reporting, doesn't happen to me for some reason...

**Comment by connyduck** [comment]
Here is the unobfuscated stacktrace. Looks like there can be conversations without statuses even though the Mastodon Api specifies them as non-nullable? https://docs.joinmastodon.org/api/entities/#conversation
```
java.lang.NullPointerException: 
  at com.keylesspalace.tusky.components.conversation.ConversationEntityKt.toEntity (ConversationEntityKt.java:169)
  at com.keylesspalace.tusky.components.conversation.ConversationEntityKt.toEntity (ConversationEntityKt.java:185)
  at com.keylesspalace.tusky.components.conversation.ConversationsRepository.insertResultIntoDb (ConversationsRepository.java:98)
  at com.keylesspalace.tusky.components.conversation.ConversationsRepository.access$insertResultIntoDb (ConversationsRepository.java:22)
  at com.keylesspalace.tusky.components.conversation.ConversationsRepository$refresh$1$onResponse$1$1.run (ConversationsRepository.java:48)
  at androidx.room.RoomDatabase.runInTransaction (RoomDatabase.java:298)
  at com.keylesspalace.tusky.components.conversation.ConversationsRepository$refresh$1$onResponse$1.run (ConversationsRepository.java:46)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
```

What does your dm timeline look like when you open it on the web? Anything weird? @bernd289

**Comment by bernd289** [comment]
@connyduck nope looks as I would expect it...

Maybe related: I had similar issues with Mastodon web and Fedilab (Mastalab) in the past.
See here:
https://github.com/tootsuite/mastodon/issues/9170
and
https://gitlab.com/tom79/mastalab/issues/581

**Comment by connyduck** [comment]
Yes, its definitely a `Conversation` with a null `lastStatus`. Must be a Mastodon bug. But we have to handle this somehow? Maybe by completely removing the conversation from the list?

**Comment by connyduck** [comment]
I tried to fix it, can you please try out this build and test if it really fixes the problem? In case it no longer crashes, please compare your Tusky DM timeline with your web DMs.
https://app.bitrise.io/artifact/11948133/p/bacda6d359060bd0dcf7a70f5bc0b982

**Comment by bernd289** [comment]
The build is working fine here!
But I can't see a difference in the DM tab, tusky vs website... There are the same threads.
