### ISSUE TITLE
Tusky stop opening

### ISSUE THREAD

**Issue by rapofran** [tuskyapp/Tusky#1052]
Hi there, I don't know what else to try. I cannot open Tusky at all. 

Here is my `adb logcat`

```
02-17 11:45:52.964   795  1740 D AudioService: Stream muted, skip playback
02-17 11:45:52.965   795 19120 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.keylesspalace.tusky/.SplashActivity bnds=[8,526][184,759] (has extras)} from uid 10028 on display 0
02-17 11:45:53.072   795 19124 I ActivityManager: START u0 {cmp=com.keylesspalace.tusky/.MainActivity} from uid 10077 on display 0
02-17 11:45:53.420  6750 10179 I JobManager: Found pending job request{id=6, tag=notifications_job_tag, transient=false}, canceling
02-17 11:45:53.483  6750 10179 D JobProxy24: Schedule periodic jobInfo success, request{id=7, tag=notifications_job_tag, transient=false}, interval 00:15:00, flex 00:15:00
02-17 11:45:53.617  6750 10225 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
02-17 11:45:53.617  6750 10225 I Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
02-17 11:45:53.617  6750 10225 I Adreno-EGL: Build Date: 02/18/17 Sat
02-17 11:45:53.617  6750 10225 I Adreno-EGL: Local Branch: 
02-17 11:45:53.617  6750 10225 I Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
02-17 11:45:53.617  6750 10225 I Adreno-EGL: Local Patches: NONE
02-17 11:45:53.617  6750 10225 I Adreno-EGL: Reconstruct Branch: NOTHING
02-17 11:45:53.621  6750 10225 I OpenGLRenderer: Initialized EGL, version 1.4
02-17 11:45:53.621  6750 10225 D OpenGLRenderer: Swap behavior 1
02-17 11:45:53.624  6750 10225 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
02-17 11:45:53.622  6750  6750 W RenderThread: type=1400 audit(0.0:598): avc: denied { read } for uid=10077 name="gpuclk" dev="sysfs" ino=11455 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-17 11:45:53.729  6750 10179 D PlatformJobService: Run job, request{id=7, tag=notifications_job_tag, transient=false}, waited 00:00:00, interval 00:15:00, flex 00:15:00
02-17 11:45:53.729  6750 10179 I JobExecutor: Executing request{id=7, tag=notifications_job_tag, transient=false}, context PlatformJobService
02-17 11:45:53.834   795  1215 I ActivityManager: Displayed com.keylesspalace.tusky/.MainActivity: +718ms (total +846ms)
02-17 11:45:54.317  6750  6761 I art     : Background sticky concurrent mark sweep GC freed 16501(1373KB) AllocSpace objects, 39(844KB) LOS objects, 30% free, 5MB/7MB, paused 9.946ms total 37.129ms
02-17 11:45:54.335  1900  1900 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-17 11:45:54.740  6750  6755 I art     : Do partial code cache collection, code=15KB, data=30KB
02-17 11:45:54.742  6750  6755 I art     : After code cache collection, code=15KB, data=30KB
02-17 11:45:54.742  6750  6755 I art     : Increasing code cache capacity to 128KB
02-17 11:45:54.893  6750  6750 D AndroidRuntime: Shutting down VM
02-17 11:45:54.902  6750  6750 E AndroidRuntime: FATAL EXCEPTION: main
02-17 11:45:54.902  6750  6750 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 6750
02-17 11:45:54.902  6750  6750 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.keylesspalace.tusky.h.x.a(SourceFile:49)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.keylesspalace.tusky.h.x.a(SourceFile:92)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.keylesspalace.tusky.a.an.a(SourceFile:127)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.keylesspalace.tusky.a.an.a(SourceFile:542)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.keylesspalace.tusky.a.at.a(SourceFile:74)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.keylesspalace.tusky.a.x.a(SourceFile:133)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.es.a(SourceFile:6781)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.fn.a(SourceFile:16823)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.fn.a(SourceFile:6019)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.fn.b(SourceFile:5858)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.do.a(SourceFile:11854)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1557)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1517)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.c(SourceFile:612)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.E(SourceFile:3924)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.z(SourceFile:3641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(SourceFile:4194)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SourceFile:625)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.onLayout(SourceFile:1915)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onLayout(SourceFile:1775)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.c(SourceFile:1183)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.a(SourceFile:870)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:889)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onLayout(SourceFile:1231)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
02-17 11:45:54.902  6750  6750 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-17 11:45:54.903  6750  6750 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-17 11:45:54.910   795   852 W ActivityManager:   Force finishing activity com.keylesspalace.tusky/.MainActivity
02-17 11:45:54.979   795 13586 I OpenGLRenderer: Initialized EGL, version 1.4
02-17 11:45:54.979   795 13586 D OpenGLRenderer: Swap behavior 1
02-17 11:45:55.103  6750 10178 I JobExecutor: Finished job{id=7, finished=true, result=SUCCESS, canceled=false, periodic=true, class=aj, tag=notifications_job_tag}
```

I've tried re-installing and had the same result.

* * * *
- Tusky Version: 4.1
- Android Version: Android 7.1.2 (LineageOS)
- Android Device: Moto G3
- Mastodon instance (if applicable): Pleroma v2.3.3
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rapofran** [comment]
Didn't know what changed but: now it crash on the `notifications` tab. (same error)

I think is a problem on my side. Sorry for the noise.

Thanks for this great app <3

**Comment by connyduck** [comment]
This looks very much like its a status with malformed markup that makes Tusky crash. Can you maybe look in the web version if you can find the culprit?

**Comment by rapofran** [comment]
Yes is something malformed, but I've checked the HTML source and did not find anything strange.
When I scroll to one specific notification it breaks tusky. (I can paste the markup here if you want)

_just needed to get some new notifications so that malformed get hidden xD_

I'm closing this issue

**Comment by rapofran** [comment]
this HTML is breaking Tusky (I'm copying it from web):

```
<div class="notification">
   <div class="status-el">
      <!----> 
      <div class="media status USER____funkwhale_AT_blog_funkwhale_audio">
         <div class="media-left">
            <a href="https://blog.funkwhale.audio/@/funkwhale/">
               <div class="still-image avatar avatar-compact">
                  <!----> <img src="https://blog.funkwhale.audio/static/media/75DABB75-C0FF-7BC1-7604-B09060FBA278.png">
               </div>
            </a>
         </div>
         <div class="status-body">
            <!----> 
            <div class="media-body container media-heading">
               <div class="media-heading-left">
                  <div class="name-and-links">
                     <h4 class="user-name">funkwhale / blog</h4>
                     <span class="links">
                        <a href="/users/15107" class="">funkwhale@blog.funkwhale.audio</a> <!----> <!---->
                     </span>
                  </div>
                  <!---->
               </div>
               <div class="media-heading-right">
                  <a href="/notice/1288060" class="timeago"><time datetime="Mon Feb 25 2019 13:03:34 GMT-0300 (Argentina Standard Time)" title="2/25/2019, 1:03:34 PM">1h</time></a> 
                  <div class="visibility-icon"><i class="icon-globe"></i></div>
                  <a href="https://blog.funkwhale.audio/~/Announcements/a-warm-welcome-to-ginny/" target="_blank" class="source_url"><i class="icon-link-ext-alt"></i></a> <!----> <!---->
               </div>
            </div>
            <!----> 
            <div class="status-content-wrapper">
               <!----> 
               <div class="status-content media-body">
                  <p><a href="https://blog.funkwhale.audio/~/Announcements/a-warm-welcome-to-ginny/">A warm welcome to Ginny!</a></p>
                  <p>Today, I'm incredibly excited to announce that <a href="http://ginny.today">Ginny</a> will be joining the project, starting immediatly. She'll work with us to ensure our community and our future organization are as inclusive, diverse and welcoming for everyone as they should be.</p>
                  <p>Her long experience with online communities will bring us the feedback and ideas we need to bring Funkwhale to the next level. She's new to our community, so please <a href="https://socialhub.network/t/intro-post-hello-funkwhale/429">give her a warm welcome</a>!</p>
                  <p>Ginny will also be the first Funkwhale contributor to be paid for her work. I'm going to share the details with you, for the sake of transparency: Ginny will work with us from February 25th to March 31st. That's five week in total, and she'll be paid 200 USD per week. We agreed on this amount and duration, based on our needs and available resources. At the end of this 5-week period, we'll discuss of the outcomes and the future of our cooperation :)</p>
                  <p>Thank you for joining us Ginny, we're looking forward to work with you!</p>
               </div>
               <!----> <a href="#" class="status-unhider">Show less</a>
            </div>
            <div class="attachments media-body"></div>
            <div class="status-actions media-body">
               <div><a href="#"><i class="icon-reply"></i></a></div>
               <div><i class="icon-retweet rt-active retweeted-empty"></i> <span>2</span></div>
               <div>
                  <i class="favorite-button fav-active icon-star-empty"></i> <!---->
               </div>
               <!---->
            </div>
         </div>
      </div>
      <!---->
   </div>
</div>
```
is a notification where I am not mentioned, but I still recieve it (don't know how this works).
I'm not following that account any more and still got this notification.

What can I do?

Thanks

**Comment by charlag** [comment]
Hey
You can clear your notifications from the web to fix it for now.

**Comment by charlag** [comment]
Would be nice if you got logs with the new Tusky version again

**Comment by rapofran** [comment]
@charlag thanks! I cleaned my notifications and now can use Tusky <3

Also in F-Droid I don't see the new version of tusky.

**Comment by charlag** [comment]
Ah, it's still not published by them, I forgot about it. Let's close it for now then if it's for the old version.
