### ISSUE TITLE
App crash upton start on chinese devices

### ISSUE THREAD

**Issue by GammaPi** [tuskyapp/Tusky#1308]
[Issue text goes here].

* * * *
- Tusky Version: 7.1
- Android Version: 9.0
- Android Device: honor v10,samsung s7 edge chinese edition
- Mastodon instance (if applicable):2.8.4

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
Log from android studio:

```
19-06-06 23:25:11.116 1368-2748/? W/WindowManager: Token{cb3b4f7 ActivityRecord{efbc8f6 u0 com.keylesspalace.tusky/.SplashActivity t2178}} failed creating starting window
    android.content.res.Resources$NotFoundException: Drawable com.keylesspalace.tusky:drawable/background_splash with resource ID #0x7f080065
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/background_splash.xml from drawable resource ID #0x7f080065
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:837)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
        at android.content.res.Resources.getDrawable(Resources.java:833)
        at android.content.Context.getDrawable(Context.java:605)
        at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:3491)
        at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:98)
        at com.android.server.wm.AppWindowContainerController.lambda$-com_android_server_wm_AppWindowContainerController_5383(AppWindowContainerController.java:164)
        at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.$m$0(Unknown Source:4)
        at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
        at android.graphics.drawable.DrawableInflater.inflateSpr(DrawableInflater.java:253)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:138)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1322)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1311)
        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:284)
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:194)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:146)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1322)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1281)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:824)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659) 
        at android.content.res.Resources.getDrawableForDensity(Resources.java:891) 
        at android.content.res.Resources.getDrawable(Resources.java:833) 
        at android.content.Context.getDrawable(Context.java:605) 
        at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:3491) 
        at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:98) 
        at com.android.server.wm.AppWindowContainerController.lambda$-com_android_server_wm_AppWindowContainerController_5383(AppWindowContainerController.java:164) 
        at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.$m$0(Unknown Source:4) 
        at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.run(Unknown Source:0) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
        at com.android.server.ServiceThread.run(ServiceThread.java:46) 





2019-06-06 23:25:11.344 26955-26955/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.keylesspalace.tusky, PID: 26955
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.keylesspalace.tusky-wI6X6ZtwMcDZWhynA6lqCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.keylesspalace.tusky-wI6X6ZtwMcDZWhynA6lqCw==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libconscrypt_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.conscrypt.NativeCryptoJni.init(SourceFile:3)
        at org.conscrypt.NativeCrypto.<clinit>(SourceFile:1)
        at org.conscrypt.NativeCrypto.checkAvailability(SourceFile:1)
        at org.conscrypt.Conscrypt.newProvider(SourceFile:1)
        at com.keylesspalace.tusky.TuskyApplication.f(SourceFile:1)
        at com.keylesspalace.tusky.TuskyApplication.onCreate(SourceFile:2)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by connyduck** [comment]
Ahh yes. I keep seeing this in crash reports but was never able to reproduce. 

Where do you download Tusky from?

**Comment by GammaPi** [comment]
It turns out to be no problem if I download apk from the website or google play.
These errors are caused by sharing installed apk between devices using wifi direct.

**Comment by connyduck** [comment]
Ok but there is nothing we can do about it, its not our fault.

**Comment by charlag** [comment]
Ooooooooh
Oooooooh

*that's* why.

You should share full (f-droid) build then
