### ISSUE TITLE
NullPointerException trying to open the app

### ISSUE THREAD

**Issue by insomnyawolf** [tuskyapp/Tusky#1520]
That was happening for several weeks in my phone.

It happens right after oppening the app if the session is active.

Logs:

https://del.dog/azatecezaj

```logcat
time: 1570173602021 msg: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference stacktrace: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference 	at com.keylesspalace.tusky.entity.Account.getName(SourceFile:1) 	at z0.f.a.b3.m1.b(SourceFile:36) 	at z0.f.a.b3.m1.a(SourceFile:1) 	at androidx.recyclerview.widget.RecyclerView$f.a(SourceFile:19) 	at androidx.recyclerview.widget.RecyclerView$u.a(SourceFile:166) 	at androidx.recyclerview.widget.LinearLayoutManager$c.a(SourceFile:10) 	at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:117) 	at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:104) 	at androidx.recyclerview.widget.LinearLayoutManager.c(SourceFile:121) 	at androidx.recyclerview.widget.RecyclerView.f(SourceFile:14) 	at androidx.recyclerview.widget.RecyclerView.d(SourceFile:9) 	at androidx.recyclerview.widget.RecyclerView.c(SourceFile:29) 	at androidx.recyclerview.widget.RecyclerView.a(SourceFile:48) 	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:6) 	at z0.f.a.g3.v1.b(SourceFile:8) 	at x0.x.d.j.a(SourceFile:4) 	at x0.x.d.z.a(SourceFile:64) 	at x0.x.d.f.run(SourceFile:6) 	at android.os.Handler.handleCallback(Handler.java:873) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:193) 	at android.app.ActivityThread.main(ActivityThread.java:6698) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

**Comment by connyduck** [comment]
What instance are you using?

**Comment by insomnyawolf** [comment]
https://fedi.absturztau.be

**Comment by connyduck** [comment]
This looks very similar to https://github.com/tuskyapp/Tusky/issues/1398, but your instance looks up to date 🤔 
Can you try deleting you notifications (with another client) please?

**Comment by insomnyawolf** [comment]
Done:
* Deleted Tusky Data and Cache
* Opened WebClient
* Mark all notifications as read
* Started Tusky And LogIn Again

Result:
The app keeps crashing with the same error
```logcat
time: 1570480610094
msg: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at com.keylesspalace.tusky.entity.Account.getName(SourceFile:1)
	at z0.f.a.b3.m1.b(SourceFile:36)
	at z0.f.a.b3.m1.a(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$f.a(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView$u.a(SourceFile:166)
	at androidx.recyclerview.widget.LinearLayoutManager$c.a(SourceFile:10)
	at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:117)
	at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:104)
	at androidx.recyclerview.widget.LinearLayoutManager.c(SourceFile:121)
	at androidx.recyclerview.widget.RecyclerView.f(SourceFile:14)
	at androidx.recyclerview.widget.RecyclerView.d(SourceFile:9)
	at androidx.recyclerview.widget.RecyclerView.c(SourceFile:29)
	at androidx.recyclerview.widget.RecyclerView.a(SourceFile:48)
	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:6)
	at z0.f.a.g3.v1.b(SourceFile:8)
	at x0.x.d.j.a(SourceFile:4)
	at x0.x.d.z.a(SourceFile:64)
	at x0.x.d.f.run(SourceFile:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

**Comment by connyduck** [comment]
Ok, so for some reason Pleroma returns `null` names for Accounts in timelines. I can try to fix it but really Pleroma shouldn't do this 🤔 
Do you have any idea which user in your timeline could cause this?

**Comment by absturztau-be** [comment]
i had another account with exactly the same issue. apparently there are notifications from users that either got deleted on my instance or don't exist anymore.
if i look at that account from fedilab i see a couple of "null followed you" notifs. deleting the notifications in fedilab fixed it for me.

i don't see anything special in pleroma logs tho

![Tusky_1570736761236_A4A73UMX6T](https://user-images.githubusercontent.com/56412233/66602157-ce05d580-eba9-11e9-8281-b91d67699276.png)

**Comment by insomnyawolf** [comment]
Yeah, look like this fixes it (at least for now) but it could be nice if the app just didnt crash so you can delete those notifications

Thanks @connyduck @absturztau-be ♥

**Comment by absturztau-be** [comment]
FYI: i filed an issue on pleroma 
https://git.pleroma.social/pleroma/pleroma/issues/1312
