### ISSUE TITLE
NOT NULL constraint failed: TimelineAccountEntity.url

### ISSUE THREAD

**Issue by MightyPork** [tuskyapp/Tusky#1792]
Getting this crash quite regularly both with vanilla Tusky and with Husky. Server is Pleroma.

```
05-17 18:40:29.353 12595 12641 W System.err: q1.a.c0.c: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: TimelineAccountEntity.url (code 1299)
05-17 18:40:29.353 12595 12641 W System.err: 	at q1.a.e0.b.y.a(SourceFile:2)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.d.j.onError(SourceFile:2)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.e.f.x.onError(SourceFile:1)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.e.f.o.b(SourceFile:9)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.w.a(SourceFile:38)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.e.f.x.run(SourceFile:1)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.r.run(SourceFile:2)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.g.r.run(SourceFile:2)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.g.r.call(SourceFile:1)
05-17 18:40:29.354 12595 12641 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-17 18:40:29.354 12595 12641 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-17 18:40:29.354 12595 12641 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-17 18:40:29.354 12595 12641 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-17 18:40:29.354 12595 12641 W System.err: 	at java.lang.Thread.run(Thread.java:764)
05-17 18:40:29.354 12595 12641 W System.err: Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: TimelineAccountEntity.url (code 1299)
05-17 18:40:29.354 12595 12641 W System.err: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
05-17 18:40:29.354 12595 12641 W System.err: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
05-17 18:40:29.354 12595 12641 W System.err: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
05-17 18:40:29.354 12595 12641 W System.err: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
05-17 18:40:29.354 12595 12641 W System.err: 	at l1.b0.a.g.i.a(SourceFile:1)
05-17 18:40:29.354 12595 12641 W System.err: 	at l1.y.d.b(SourceFile:3)
05-17 18:40:29.354 12595 12641 W System.err: 	at n1.f.a.c2.n0.a(SourceFile:11)
05-17 18:40:29.354 12595 12641 W System.err: 	at n1.f.a.c2.n0.a(SourceFile:2)
05-17 18:40:29.354 12595 12641 W System.err: 	at n1.f.a.j2.i.call(SourceFile:46)
05-17 18:40:29.354 12595 12641 W System.err: 	at q1.a.e0.e.f.o.b(SourceFile:4)
05-17 18:40:29.354 12595 12641 W System.err: 	... 10 more
05-17 18:40:29.358   651  2249 W ActivityManager:   Force finishing activity com.keylesspalace.tusky/.MainActivity
05-17 18:40:29.370   651   667 I ActivityManager: Showing crash dialog for package com.keylesspalace.tusky u0
```

**Comment by charlag** [comment]
Apparently account doesn't have a URL? What gives?

**Comment by a1batross** [comment]
I was looking into this before and it doesn't look like a Tusky bug. It happens only on outdated Pleroma releases, I suggest you upgrade your instance.

I did a workaround but it does not comply to Mastodon API and in fact, it doesn't completely work either.

**Comment by MightyPork** [comment]
Update to what, do you know if the fix is in Stable?

**Comment by charlag** [comment]
piggo.space is on 2.0.0, latest Pleroma is 2.0.5. I checked changelog but didn't find mention of the fix. Maybe still worth a try to update?

**Comment by MightyPork** [comment]
updated to 2.0.5, i'll reopen this if the issue happens again
