### ISSUE TITLE
Crash when opening the compose interface

### ISSUE THREAD

**Issue by autumnontape** [tuskyapp/Tusky#1841]
When I press the compose button, Tusky immediately crashes and Android tells me it has stopped. The same thing happens when I tap a draft to open it.

* * * *
- Tusky Version: 11.0 (F-Droid)
- Android Version: 7.1.1
- Android Device: ZTE Axon 7
- Mastodon instance (if applicable): [snouts.online](https://snouts.online/)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi,
I'm afraid we can't do much without more info. We would need some debug log to find it out. With play version it would be reported but with F-Droid one it's not.

**Comment by autumnontape** [comment]
Let's see, this snippet from logcat seems interesting. I don't know what's up with all the obfuscated symbols, though.

<details>

```
06-21 14:30:13.480  2813 21618 I ActivityManager: START u0 {cmp=com.keylesspalace.tusky/.components.compose.ComposeActivity} from uid 10154 on display 0
06-21 14:30:13.480  2813 21618 D ActivityTrigger: Activity is Triggerred in full screen 
06-21 14:30:13.480  2813 21618 D CompatibilityInfo: mCompatibilityFlags - 0
06-21 14:30:13.480  2813 21618 D CompatibilityInfo: applicationDensity - 640
06-21 14:30:13.480  2813 21618 D CompatibilityInfo: applicationScale - 1.0
06-21 14:30:13.480  2813 21618 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
06-21 14:30:13.490  2398  2398 I cnss-daemon: RTM_NEWNEIGH message received: 28
06-21 14:30:13.490  2398  2398 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
06-21 14:30:13.490  2813 21618 D ActivityManager: --zc to bg, ProcessRecord{7198a9d 21248:com.keylesspalace.tusky/u0a154} rx/tx = 20164218 1645505
06-21 14:30:13.490  2813  2936 D CompatibilityInfo: mCompatibilityFlags - 0
06-21 14:30:13.490  2813  2936 D CompatibilityInfo: applicationDensity - 640
06-21 14:30:13.490  2813  2936 D CompatibilityInfo: applicationScale - 1.0
06-21 14:30:13.500  2813  2936 I ZTEAppProfile: apk (com.keylesspalace.tusky) at top
06-21 14:30:13.500 21248 21248 D Typeface: fontPath: 
06-21 14:30:13.510 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@938d04d
06-21 14:30:13.510 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5365702
06-21 14:30:13.520 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@383b067
06-21 14:30:13.520 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@57bae14
06-21 14:30:13.520 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b10ec03
06-21 14:30:13.520 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b6f9780
06-21 14:30:13.520 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4c439fe
06-21 14:30:13.520 21248 21248 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9ac455f
06-21 14:30:13.550 21248 21586 E AndroidRuntime: FATAL EXCEPTION: c2.r0 Dispatcher
06-21 14:30:13.550 21248 21586 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 21248
06-21 14:30:13.550 21248 21586 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i0$a.a(SourceFile:94)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.u0$a.a(SourceFile:6)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.d.c.a(SourceFile:12)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.h.a(SourceFile:21)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.a.a(SourceFile:23)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.h.a(SourceFile:21)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.j.a(SourceFile:30)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.h.a(SourceFile:21)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at v1.f.a.b2.a.a(SourceFile:36)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.h.a(SourceFile:21)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at t1.e0.t0.a(SourceFile:356)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at t1.e0.a.a(lambda)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.g.h.a(SourceFile:21)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.f.j.b(SourceFile:25)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at c2.i1.f.g.run(SourceFile:12)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-21 14:30:13.550 21248 21586 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
06-21 14:30:13.550  2813  9458 W ActivityManager:   Force finishing activity com.keylesspalace.tusky/.components.compose.ComposeActivity
06-21 14:30:13.560  2813  9458 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
06-21 14:30:13.560  2813  9458 D ActivityManager: --zc to bg, ProcessRecord{7198a9d 21248:com.keylesspalace.tusky/u0a154} rx/tx = 20164218 1645628
06-21 14:30:13.560  2813  9458 W ActivityManager:   Force finishing activity com.keylesspalace.tusky/.MainActivity
```
</details>

Is that helpful? Is there some other way of getting a stack trace I should use?

**Comment by charlag** [comment]
That's as much as I could ask, thanks!
Probably because it's an F-Droid build we can't deobfuscate it. We would need a debug build for that.
I wonder if it's something about the instance that causes this.

**Comment by autumnontape** [comment]
Indeed, when I log in to my old account on octodon.social and press the compose button, it works fine. When I switch back to my snouts.online account and press the compose button, the crash still happens.

**Comment by charlag** [comment]
We load some instance info at this point like emojis and char limits, it seems like the error is URL related so I would checks snouts.online/api/v1/instance. I can do it tomorrow.

**Comment by connyduck** [comment]
I got an account on snouts.online and it works just fine. From the stacktrace my first guess would be `/api/v1/custom_emojis`, which we also load on the compose screen, has invalid emoji urls. Can you try if cleaning app data and logging in again resolves the issue? The emojis are cached

**Comment by autumnontape** [comment]
Clearing the app cache fixed it.
