### ISSUE TITLE
Crash when adding an image caption

### ISSUE THREAD

**Issue by codl** [tuskyapp/Tusky#2166]
When opening the image caption dialog, the app crashes. Doesn't seem to happen with every image, here is [one that i used](https://user-images.githubusercontent.com/315139/118796373-d81aaa80-b89b-11eb-8379-d4b26df6c0fd.jpg)

<details>
<summary>Stack trace</summary>
<pre>
java.lang.RuntimeException: Canvas: trying to draw too large(302907392bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at android.view.View.draw(View.java:22527)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.updateDisplayListIfDirty(View.java:21386)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.View.draw(View.java:22255)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
	at android.view.View.draw(View.java:22530)
	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
	at android.view.View.updateDisplayListIfDirty(View.java:21395)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4219)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3933)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2046)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8349)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
	at android.view.Choreographer.doFrame(Choreographer.java:813)
	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:985)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7858)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
</pre></details>

https://user-images.githubusercontent.com/315139/118796112-938f0f00-b89b-11eb-83cb-a1dec72f31d3.mp4

* * * *
- Tusky Version: 15.0, from the Play Store
- Android Version: 11
- Android Device: Poco X3 NFC
- Mastodon instance (if applicable): tested on chitter.xyz, donphan.social. Likely works everywhere

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I know, sorry for that :(
https://github.com/tuskyapp/Tusky/pull/2165
