### ISSUE TITLE
Crash when adding an image description

### ISSUE THREAD

**Issue by divergentdave** [tuskyapp/Tusky#2180]
When I try to add a description to an image, Tusky crashes. I can reproduce this reliably, and another Tusky user on the same instance as me has also encountered the same problem. This appears to be different from #2149, both because I can reproduce with small images, and because 15.0 postdates that PR.

* * * *
- Tusky Version: 15.0
- Android Version: 11
- Android Device: Pixel 3A
- Mastodon instance (if applicable): mspsocial.net

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by divergentdave** [comment]
<details>
<summary>
Stack trace
</summary>

```
05-27 14:15:35.247 14275 14275 D AndroidRuntime: Shutting down VM
05-27 14:15:35.248 14275 14275 E AndroidRuntime: FATAL EXCEPTION: main
05-27 14:15:35.248 14275 14275 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 14275
05-27 14:15:35.248 14275 14275 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(213417984bytes) bitmap.
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1436)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22350)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21217)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22081)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.draw(View.java:22353)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-27 14:15:35.248 14275 14275 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2165
