### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AnonymousWebHacker** [tuskyapp/Tusky#2385]
The app with the latest update from the play store crashes and does not open
Android: 7.1
Tusky : 16.0 last version

**Comment by connyduck** [comment]
Do you remember what you did before the problem started?
Can you maybe retrieve the log output from your device so we can see the stacktrace?

**Comment by AnonymousWebHacker** [comment]
Just update the app, and it crashes when I try to open it, it won't let me open it anymore.
I had to downgrade it to make it work for me, I installed the previous version.

As for the debug, I did not know that this could be done, if you have the kindness to explain me, I will gladly pass you the logs. Could it be developer mode, debug?

**Comment by connyduck** [comment]
Can you reproduce this behavior? Does it crash again when you upgrade again?

You enable usb debugging in the developer settings, connect your device to a computer, open Android studio and in the "logcat" tab you should see the logs.

**Comment by AnonymousWebHacker** [comment]
![Screenshot_20220318-140754](https://user-images.githubusercontent.com/43164089/159059574-7a102f75-b50b-4f9f-90ef-18e346a0f9cb.png)

**Comment by connyduck** [comment]
Do you have "Animate Avatars" and/or "Animate custom emojis" enabled?

**Comment by AnonymousWebHacker** [comment]
I don't really remember, but I think they are activated.

Another strange thing, the notifications keep coming in, but when I open the application, it closes

**Comment by MayMeow** [comment]
Hi there, I have similar problem and maybe following debug trace can help

```bash
2022-03-22 03:13:23.120 29815-30040/? E/lace.tusky.tes: ----- class 'Lcom/github/penfeizhou/animation/gif/decode/GifFrame;' cl=0x13bd7988 -----
      objectSize=252 (120 from super)
      access=0x0008.0001
      super='java.lang.Class<g4.a>' (cl=0x13bd7988)
      vtable (3 entries, 1 in super):
         0: android.graphics.Bitmap com.github.penfeizhou.animation.gif.decode.GifFrame.a(android.graphics.Canvas, android.graphics.Paint, int, android.graphics.Bitmap, l4.a)
         1: android.graphics.Bitmap com.github.penfeizhou.animation.gif.decode.GifFrame.b(android.graphics.Canvas, android.graphics.Paint, int, android.graphics.Bitmap, j4.b)
         2: void com.github.penfeizhou.animation.gif.decode.GifFrame.c(int[], int)
      direct methods (3 entries):
         0: void com.github.penfeizhou.animation.gif.decode.GifFrame.<clinit>()
         1: void com.github.penfeizhou.animation.gif.decode.GifFrame.<init>(j4.a, i4.c, i4.i, i4.j)
         2: void com.github.penfeizhou.animation.gif.decode.GifFrame.uncompressLZW(j4.a, int[], int, int[], int, int, int, boolean, byte[])
      static fields (1 entries):
         0: java.lang.ThreadLocal com.github.penfeizhou.animation.gif.decode.GifFrame.m
      instance fields (6 entries):
         0: int com.github.penfeizhou.animation.gif.decode.GifFrame.g
         1: int com.github.penfeizhou.animation.gif.decode.GifFrame.h
         2: i4.c com.github.penfeizhou.animation.gif.decode.GifFrame.i
         3: int com.github.penfeizhou.animation.gif.decode.GifFrame.j
         4: int com.github.penfeizhou.animation.gif.decode.GifFrame.k
         5: boolean com.github.penfeizhou.animation.gif.decode.GifFrame.l
2022-03-22 03:13:23.120 29815-30040/? E/lace.tusky.tes: Failed to register native method com.github.penfeizhou.animation.gif.decode.GifFrame.uncompressLZW(Lcom/github/penfeizhou/animation/gif/io/GifReader;[II[IIIIZ[B)V in base.apk
2022-03-22 03:13:23.120 29815-30040/? E/AndroidRuntime: FATAL EXCEPTION: FrameDecoderExecutor-0
    Process: com.keylesspalace.tusky.test, PID: 29815
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~DsuqTARFQwjiAh9HEV38CA==/com.keylesspalace.tusky.test-STROd2dq_XOSNDUpKMVbUQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libanimation-decoder-gif.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.github.penfeizhou.animation.gif.decode.GifFrame.<clinit>(SourceFile:1)
        at i4.g.m(SourceFile:34)
        at androidx.appcompat.widget.j.run(SourceFile:32)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-03-22 03:13:23.137 27293-27347/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
2022-03-22 03:13:23.138 28799-2497/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
2022-03-22 03:13:23.138 29974-3475/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
2022-03-22 03:13:23.140 28799-30481/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
2022-03-22 03:13:23.170 27807-27872/? E/FrameworkListener: read() failed (Connection reset by peer)
```

**Comment by connyduck** [comment]
Issue identified and reported here https://github.com/penfeizhou/APNG4Android/issues/142

**Comment by connyduck** [comment]
The stacktrace by @MayMeow is from a crash in nightly, the crash experienced by @AnonymousWebHacker might be different as they are not on nightly, right?

**Comment by AnonymousWebHacker** [comment]
> The stacktrace by @MayMeow is from a crash in nightly, the crash experienced by @AnonymousWebHacker might be different as they are not on nightly, right?

Anyway, I don't think that's the problem.

Go into settings, and clear cache and app data, and it didn't work. When I open, the app closes

**Comment by connyduck** [comment]
A crash on launch with no user signed in? That is definitely not a gif related crash then. 
Can you help me debug this a little bit more, @AnonymousWebHacker?
It would be interesting to see if the [Tusky Nightly](https://play.google.com/store/apps/details?id=com.keylesspalace.tusky.test) and the [Tusky 16 apk from our homepage](https://tusky.app) have the same behavior.

**Comment by AnonymousWebHacker** [comment]
I am using the PlayStore version, right now I just installed the update from yesterday the 24th and the same thing, it does not allow me to open the apk.

Let me try with Fdroid without Google Play services or try the official version of Tusky blue

**Comment by AnonymousWebHacker** [comment]
Tusky official version (blue) opens perfectly and I can use the app, but not the dark version dev (Nightly).

**Comment by AnonymousWebHacker** [comment]
> Tusky official version (blue from Google play ) opens perfectly and I can use the app, but not the dark version dev (Nightly).

@connyduck Las update Tusky Official and Nightly , to work, they are still crashed

**Comment by connyduck** [comment]
So Tusky 17.0 beta 1 is still crashing for you? With all data cleared?
I wish i had a stacktrace because I have no clue what this could be. There are also 0 reports in the Google Play console that fit the description.

**Comment by connyduck** [comment]
Nightly will get an update (`17.0 beta 1-d4eeef99`) soon with that might fix this. Please test and report back @AnonymousWebHacker

**Comment by sersorrel** [comment]
I'm getting a crash on startup with Tusky 16.0:

<details><summary>adb logcat</summary>

```
04-06 03:02:16.109 29294 29294 E AndroidRuntime: FATAL EXCEPTION: main
04-06 03:02:16.109 29294 29294 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 29294
04-06 03:02:16.109 29294 29294 E AndroidRuntime: com.google.gson.s: Apr 6, 2022 16:45:42
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.google.gson.internal.bind.DateTypeAdapter.b(SourceFile:8)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:10)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.google.gson.Gson.c(SourceFile:9)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.google.gson.Gson.b(SourceFile:1)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at r6.s.n(SourceFile:26)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at r6.s.k(SourceFile:2)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at g1.z1.b(SourceFile:13)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at g1.v.a(SourceFile:35)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at i6.p.p(SourceFile:15)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at w9.i.n(SourceFile:1)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at f9.a.h(SourceFile:3)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at t9.r0.run(SourceFile:22)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at t9.a1.j0(SourceFile:8)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at t9.k.p(SourceFile:16)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at v9.b.h(SourceFile:2)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at v9.k.p(SourceFile:18)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at v9.j.j(SourceFile:1)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at g1.n3.d(SourceFile:42)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at g1.y2.n(Unknown Source:11)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at f9.a.h(SourceFile:3)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at t9.r0.run(SourceFile:22)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: Caused by: java.text.ParseException: Failed to parse date ["Apr 6, 2022 16:45:42"]: Invalid number: Apr
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at q5.a.b(SourceFile:58)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at com.google.gson.internal.bind.DateTypeAdapter.b(SourceFile:7)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	... 28 more
04-06 03:02:16.109 29294 29294 E AndroidRuntime: Caused by: java.lang.NumberFormatException: Invalid number: Apr
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at q5.a.c(SourceFile:3)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	at q5.a.b(SourceFile:2)
04-06 03:02:16.109 29294 29294 E AndroidRuntime: 	... 29 more
```

</details>

It doesn't happen on nightly 17.0 beta 1-d4eeef99, and after I cleared data and logged in again it's stopped happening on 16.0 too...

**Comment by connyduck** [comment]
What server is that on @sersorrel?

**Comment by sersorrel** [comment]
@connyduck https://hellsite.site

**Comment by modelmat** [comment]
> Nightly will get an update (`17.0 beta 1-d4eeef99`) soon that might fix this. Please test and report back @AnonymousWebHacker 

Currently nightly on play store (& the one in releases? that seems older though) both crash on startup for me.

**Comment by AnonymousWebHacker** [comment]
> Looks like I'm reverting to 15.0 to get a usable app...
Since the last 16.x and 17.x updates, I have not been able to open any of the two versions (official and nightly)

**Comment by connyduck** [comment]
Does one of you have an **Asus ZenFone Max Plus M1** or an **Huawei M3**? I see weird crashes for those devices in the Google Play console.

**Comment by modelmat** [comment]
Nope, I have an OPPO. I tend to use F-droid builds anyway... (Though nightly is g-play only?)

**Comment by AnonymousWebHacker** [comment]
Movile: Alcatel A3 , Android 7
Tablet: Samsung Galaxy TabA, android 6.0.1

**Comment by connyduck** [comment]
I think I finally fixed it. A resource config issue caused crashes on Android 7.1 and lower, for Tusky 16.0 and up.
