### ISSUE TITLE
Tusky crashes when trying to view a notification

### ISSUE THREAD

**Issue by rudolfmu** [tuskyapp/Tusky#2441]
Tusky crashes when i try to view a specific notification.
Details:
https://fosstodon.org/web/@rudolf/108139387376584278
Logcat:
<<< log_count = 39 >>>
[04-16 21:25:03.615 1326:1326 D/PhoneStatusBar]
disable: < expand icons* alerts system_info* back home recent clock search quick_settings >

[04-16 21:25:18.652 755:755 V/NotificationService]
pkg=com.dp.logcatapp canInterrupt=false intercept=true

[04-16 21:25:22.125 755:2546 I/ActivityManager]
START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10033 on display 0

[04-16 21:25:22.152 17399:17399 D/LogcatReader]
[Logcat] onActivityInBackground

[04-16 21:25:22.301 755:765 I/art]
Background partial concurrent mark sweep GC freed 71079(4MB) AllocSpace objects, 15(364KB) LOS objects, 33% free, 13MB/20MB, paused 1.871ms total 126.904ms

[04-16 21:25:24.359 755:2553 E/ActivityManager]
applyOptionsLocked: Unknown animationType=0

[04-16 21:25:26.760 17483:17488 I/art]
Do full code cache collection, code=441KB, data=505KB

[04-16 21:25:26.762 17483:17488 I/art]
Starting a blocking GC JitCodeCache

[04-16 21:25:26.762 17483:17488 I/art]
After code cache collection, code=385KB, data=390KB

[04-16 21:25:27.226 17483:17483 D/AndroidRuntime]
Shutting down VM

[04-16 21:25:27.229 17483:17483 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.keylesspalace.tusky, PID: 17483
java.lang.NullPointerException: Attempt to read from field 'boolean g7.g.d' on a null object reference
	at w5.s0.O(SourceFile:1)
	at w5.z.w(SourceFile:182)
	at w5.z.n(SourceFile:1)
	at l1.h1.a(SourceFile:9)
	at l1.a2.j(SourceFile:162)
	at l1.s0.c(SourceFile:9)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.T0(SourceFile:12)
	at androidx.recyclerview.widget.LinearLayoutManager.l0(SourceFile:119)
	at androidx.recyclerview.widget.RecyclerView.r(SourceFile:57)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:12)
	at androidx.recyclerview.widget.RecyclerView.n(SourceFile:23)
	at l1.h2.run(SourceFile:5)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

[04-16 21:25:27.233 755:1561 W/ActivityManager]
  Force finishing activity com.keylesspalace.tusky/.MainActivity

[04-16 21:25:27.236 17483:18453 I/System.out]
[java.net.SocketException: Software caused connection abort, java.net.SocketException: Software caused connection abort, java.net.SocketException: Software caused connection abort]

[04-16 21:25:27.300 755:8674 I/OpenGLRenderer]
Initialized EGL, version 1.4

[04-16 21:25:27.300 755:8674 D/OpenGLRenderer]
Swap behavior 1

[04-16 21:25:27.585 755:1561 W/ActivityManager]
  Force finishing activity com.keylesspalace.tusky/.MainActivity

[04-16 21:25:27.592 755:1561 E/ActivityManager]
Found activity ActivityRecord{e334d6b u0 com.keylesspalace.tusky/.MainActivity t33345 f} in proc activity list using null instead of expected ProcessRecord{c537492 17483:com.keylesspalace.tusky/u0a298}

[04-16 21:25:27.626 755:1561 I/ActivityManager]
Killing 17483:com.keylesspalace.tusky/u0a298 (adj 199): crash

[04-16 21:25:27.628 755:1561 D/ActivityManager]
cleanUpApplicationRecord -- 17483

[04-16 21:25:27.641 755:788 W/InputEventReceiver]
Attempted to finish an input event but the input event receiver has already been disposed.

[04-16 21:25:27.644 755:788 W/ViewRootImpl[tusky]]
Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=179.72539, y[0]=549.20844, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=4896651, downTime=4896620, deviceId=4, source=0x1002 }

[04-16 21:25:27.645 755:788 W/InputEventReceiver]
Attempted to finish an input event but the input event receiver has already been disposed.

[04-16 21:25:27.687 755:1259 W/InputDispatcher]
channel 'c89fee3 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[04-16 21:25:27.687 755:1259 E/InputDispatcher]
channel 'c89fee3 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[04-16 21:25:27.699 755:1763 D/GraphicsStats]
Buffer count: 15

[04-16 21:25:27.699 755:2553 D/ConnectivityService]
ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=22, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@f611c8c)

[04-16 21:25:27.700 755:1275 D/ConnectivityService]
releasing NetworkRequest [ TRACK_DEFAULT id=22, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]

[04-16 21:25:27.707 755:1275 E/ConnectivityService]
RemoteException caught trying to send a callback msg for NetworkRequest [ TRACK_DEFAULT id=22, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]

[04-16 21:25:27.712 755:771 W/InputMethodManagerService]
Got RemoteException sending setActive(false) notification to pid 17483 uid 10298

[04-16 21:25:27.714 755:2546 I/WindowManager]
WIN DEATH: Window{c89fee3 u0 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity}

[04-16 21:25:27.714 755:2546 W/InputDispatcher]
Attempted to unregister already unregistered input channel 'c89fee3 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server)'

[04-16 21:25:27.815 755:811 W/AppOps]
Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0

[04-16 21:25:28.240 2598:2796 W/OpenGLRenderer]
Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

[04-16 21:25:28.240 2598:2796 W/OpenGLRenderer]
Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

[04-16 21:25:29.838 755:2541 I/ActivityManager]
START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10033 on display 0

[04-16 21:25:32.274 755:2548 E/ActivityManager]
applyOptionsLocked: Unknown animationType=0

[04-16 21:25:32.312 17399:17399 D/LogcatReader]
[Logcat] onActivityInForeground

[04-16 21:25:32.312 17399:17399 D/LogcatReader]
[Logcat] Posting pending logs

[04-16 21:25:32.445 17399:17399 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

* * * *
- Tusky Version: 9,11,13,15,17.0
- Android Version: 10, 7.1.2 (LOS)
- Android Device: Xiaomi, BQ
- Mastodon instance (if applicable):fosstodon.org
- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
And the stacktrace is from 17.0?
