### ISSUE TITLE
Crash when opening app ("Failed to parse date")

### ISSUE THREAD

**Issue by z3ntu** [tuskyapp/Tusky#2476]
Since a few days when opening Tusky it crashes pretty much immediately after opening. I assume app data reset will "fix" it. Here's the stack trace:
```
04-28 15:15:40.426 13527 13527 E AndroidRuntime: FATAL EXCEPTION: main
04-28 15:15:40.426 13527 13527 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 13527
04-28 15:15:40.426 13527 13527 E AndroidRuntime: com.google.gson.q: Failed parsing 'Apr 26, 2022 23:40:26' as Date; at path $.expires_at
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.google.gson.internal.bind.DateTypeAdapter.b(SourceFile:9)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:9)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.google.gson.k.c(SourceFile:9)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.google.gson.k.b(SourceFile:1)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at t6.t.o(SourceFile:29)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at t6.t.l(SourceFile:2)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at i1.n1.b(SourceFile:13)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at i1.x3.b(SourceFile:14)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at g9.d.B(SourceFile:14)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at z9.l.o(SourceFile:1)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at i9.a.h(SourceFile:3)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at w9.g0.run(SourceFile:22)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at w9.o0.k0(SourceFile:8)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at w9.i.p(SourceFile:16)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at y9.b.j(SourceFile:2)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at y9.k.o(SourceFile:18)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at y9.j.i(SourceFile:1)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at i1.e3.f(SourceFile:40)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at i1.n2.o(SourceFile:1)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at i9.a.h(SourceFile:3)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at w9.g0.run(SourceFile:22)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7715)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
04-28 15:15:40.426 13527 13527 E AndroidRuntime: Caused by: java.text.ParseException: Failed to parse date ["Apr 26, 2022 23:40:26"]: Invalid number: Apr 
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at s5.a.b(SourceFile:58)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at com.google.gson.internal.bind.DateTypeAdapter.b(SourceFile:8)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        ... 27 more
04-28 15:15:40.426 13527 13527 E AndroidRuntime: Caused by: java.lang.NumberFormatException: Invalid number: Apr 
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at s5.a.c(SourceFile:3)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        at s5.a.b(SourceFile:2)
04-28 15:15:40.426 13527 13527 E AndroidRuntime:        ... 28 more
```

Let me know if I can assist by gathering more logs or data.

* * * *
- Tusky Version: 17.0
- Android Version: 11
- Android Device: FP4
- Mastodon instance (if applicable): fosstodon.org

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by z3ntu** [comment]
Oh I actually did very briefly for testing something (24h->12h->24h).
