### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by TheLastProject** [tuskyapp/Tusky#2564]
For some reason my Tusky started to crash on launch. I was still running it last night just fine. Given I am logged into my account, maybe a bad toot is crashing Tusky? Just an idea though.

Crash log:
```
FATAL EXCEPTION: main
Process: com.keylesspalace.tusky, PID: 8728
java.lang.RuntimeException: Unable to create application com.keylesspalace.tusky.TuskyApplication: java.lang.NullPointerException: Attempt to get length of null array
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at l9.j.Z0(SourceFile:1)
	at g8.c.<init>(SourceFile:7)
	at com.keylesspalace.tusky.TuskyApplication.onCreate(SourceFile:122)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
	... 8 more
```

I have cleared the app's cache but it made no difference.

* * * *
- Tusky Version: 18.0
- Android Version: 11 (LineageOS for microG)
- Android Device: Fairphone 3
- Mastodon instance (if applicable): social.tchncs.de

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by TheLastProject** [comment]
Rebooting my phone fixed it. Weird, but makes it not reproducible so I'll close this again.

**Comment by connyduck** [comment]
this should no longer happen since https://github.com/tuskyapp/Tusky/pull/2553
