### ISSUE TITLE
crash few seconds after opening app

### ISSUE THREAD

**Issue by theotheroracle** [tuskyapp/Tusky#2775]
after logging into botsin.space app crashes a few seconda after opening it every time ( im using unified push, no  gplay services )

```
type: crash
osVersion: OnePlus/OnePlus7T/OnePlus7T:12/SQ3A.220705.004/eng.emy.20221009.051326:user/release-keys
package: com.keylesspalace.tusky:94
process: com.keylesspalace.tusky

android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: AccountEntity.pushServerKey (code 1299 SQLITE_CONSTRAINT_NOTNULL)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at q1.f.T(Unknown Source:2)
	at k1.i.g(SourceFile:3)
	at s6.b.i(SourceFile:3)
	at s6.d.c(SourceFile:2)
	at g6.g.o(SourceFile:56)
	at s9.a.i(SourceFile:3)
	at ia.h0.run(SourceFile:22)
	at na.e.run(SourceFile:2)
	at pa.i.run(SourceFile:1)
	at pa.a.run(SourceFile:15)
	Suppressed: ia.f0: [q1{Cancelling}@e9da070, Dispatchers.Default]

```
* * * *
- Tusky Version: 19.0
- Android Version: 12 ( divest os )
- Android Device: oneplus 7T
- Mastodon instance (if applicable): botsin.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I think this is a misconfiguration of botsin.space. Can you tell your admins to check if they have generated vapid keys? https://docs.joinmastodon.org/admin/config/

**Comment by theotheroracle** [comment]
this seems to have resolved it ! could this fail more gracefully though ?

**Comment by kdltr** [comment]
I asked the admin to regenerate vapid keys, they did, and the crash still happens.

**Comment by kdltr** [comment]
> I asked the admin to regenerate vapid keys, they did, and the crash still happens.

turns out it was still a configuration error… sorry for the noise :sweat_smile:

**Comment by nikclayton** [comment]
What was the error? We might need be able to show a useful error message instead of crashing.
