### ISSUE TITLE
reproducible crash

### ISSUE THREAD

**Issue by quantenzitrone** [tuskyapp/Tusky#4164]
## Steps to reproduce:
- Open any toot with text
- long click to mark some text
- long click on that marked text again without dragging
-  -> crash

https://github.com/tuskyapp/Tusky/assets/74491719/cc57a1ff-0bef-4b0f-8450-d7d3e218e90b

## Stack Trace
```java
FATAL EXCEPTION: main
Process: com.keylesspalace.tusky, PID: 24428
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:442)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:163)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:152)
	at android.text.SpannableString.setSpan(SpannableString.java:46)
	at android.text.Selection.setSelection(Selection.java:76)
	at android.widget.Editor$SelectionModifierCursorController.resetDragAcceleratorState(Editor.java:5613)
	at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:5450)
	at android.widget.Editor.onTouchEvent(Editor.java:1370)
	at android.widget.TextView.onTouchEvent(TextView.java:9679)
	at com.keylesspalace.tusky.view.ClickableSpanTextView.onTouchEvent(SourceFile:74)
	at android.view.View.dispatchTouchEvent(View.java:11808)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3022)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:449)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
	at g.b0.f(SourceFile:3)
	at g.b0.dispatchTouchEvent(SourceFile:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:411)
	at android.view.View.dispatchPointerEvent(View.java:12052)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4973)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4783)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4368)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4334)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4461)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4342)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4518)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4368)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4334)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4342)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6909)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6883)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6840)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7027)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

* * * *
- Tusky Version: 24.0
- Android Version: 8.1
- Android Device: Shift6m
- Mastodon instance (if applicable): fosstodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by fin-w** [comment]
I can't reproduce this on Android 13, in case that's helpful. Text reselects just fine.

**Comment by connyduck** [comment]
Oh wow I have seen this crash in the crash logs for ages but could never figure out what causes it. Thank you very much for reporting!
I can reproduce it only on an emulator with Android 8.1 though, so it might be an Android 8.1 specific issue that is not fixable but I will definitely try!

**Comment by connyduck** [comment]
Yeah so it definitely is a platform bug but I found a workaround
