### ISSUE TITLE
Crash on Tusky 1.6.0

### ISSUE THREAD

**Issue by Nuntius0** [tuskyapp/Tusky#583]
Steps to reproduce:
- Update from Tusky 1.5.2 via F-Droid
- Open Tusky
- Crash! So sad.

* * * *
Metadata:
- Tusky Version: 1.6.0 (F-Droid)
- Android Version: 7.1.2 February patch level
- Android Device: LG G6 (h870)
- LineageOS 14.1, rooted, no Gapps or microG
- Mastodon instance (if applicable): mastodon.club (on  v1.4.1, rather outdated I know)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Nuntius0** [comment]
And here's the log:

`FATAL EXCEPTION: main
Process: com.keylesspalace.tusky, PID: 12801
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.keylesspalace.tusky.g.y.a(ViewDataUtils.java:43)
	at com.keylesspalace.tusky.c.s$1.a(TimelineFragment.java:1141)
	at com.keylesspalace.tusky.g.t.add(PairedList.java:64)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
	at com.keylesspalace.tusky.c.s.a(TimelineFragment.java:751)
	at com.keylesspalace.tusky.c.s.a(TimelineFragment.java:15675)
	at com.keylesspalace.tusky.c.s$7.onResponse(TimelineFragment.java:620)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by charlag** [comment]
Oh noes! Thanks for reporting

**Comment by connyduck** [comment]
Seems like somebody (me) did not check Android Studio warnings 🙄
Also seems to be only a problem on old instances like yours.
fixed https://github.com/tuskyapp/Tusky/commit/df5e3a16217e42e3028785d454df30b2c9d50bf4
