### ISSUE TITLE
Crash: ComposeActvity, no network connection, emojis

### ISSUE THREAD

**Issue by Nuntius0** [tuskyapp/Tusky#627]
Tusky crashes when you open the ComposeActivity when no network connection is available, probably because it can't fetch the custom emojis.

**Steps to reproduce:**
1. Don't have internet access (enable flight mode, go deep into the woords, or just travel with Deutsche Bahn)
2. Open the compose activity (with the intention to compose a toot that you want to save and post later)
3. Observe crash: immediately when on flight mode; after more or less exactly one minute when flight mode is off but no network connection available

_Actual result:_ Crash
_Expected result:_ The emoji buttom stays grayed out, but I can continue to draft a toot.

* * * *
- Tusky Version: 1.7.0
- Android Version: 7.1.2
- Android Device: LG G6 (h870)
- Mastodon instance (if applicable): 

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Logcat:

```
FATAL EXCEPTION: main
Process: com.keylesspalace.tusky, PID: 27390
java.lang.IllegalStateException: Gson().fromJson(emojiLis…n<List<Emoji>>() {}.type) must not be null
	at com.keylesspalace.tusky.db.g.a(InstanceDao_Impl.java:2038)
	at com.keylesspalace.tusky.ComposeActivity.b(ComposeActivity.java:13444)
	at com.keylesspalace.tusky.ComposeActivity$4.onFailure(ComposeActivity.java:296)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by connyduck** [comment]
Thx for reporting, but this has already been fixed and will be in the next release https://github.com/tuskyapp/Tusky/commit/aecdbda3753876cca5d9fffae33bf22d8b208d92
