### ISSUE TITLE
Error when trying to log in

### ISSUE THREAD

**Issue by kenrestivo** [tuskyapp/Tusky#680]
```
java.net.ProtocolException: Too many follow-up requests: 21
	at d.a.c.j.a(RetryAndFollowUpInterceptor.java:171)
	at d.a.c.g.a(RealInterceptorChain.java:147)
	at d.a.c.g.a(RealInterceptorChain.java:121)
	at com.keylesspalace.tusky.network.a.a(InstanceSwitchAuthInterceptor.java:65)
	at d.a.c.g.a(RealInterceptorChain.java:147)
	at d.a.c.g.a(RealInterceptorChain.java:121)
	at com.keylesspalace.tusky.g.t.a(Unknown Source)
	at d.a.c.g.a(RealInterceptorChain.java:147)
	at d.a.c.g.a(RealInterceptorChain.java:121)
	at d.y.f(RealCall.java:200)
	at d.y$a.b(RealCall.java:147)
	at d.a.b.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

can't login initially or at all

**Comment by kenrestivo** [comment]
samsung galaxy tab, latest tusky from f-droid, hub.spaz.org pub

**Comment by kenrestivo** [comment]
Nevermind, was server configuration issue. Have oauth2 problems now, but will open new ticket for that.
