### ISSUE TITLE
Crash of Compose Activity

### ISSUE THREAD

**Issue by Nuntius0** [tuskyapp/Tusky#941]
Crashes after opening the compose view. Timelines are all working fine.
```
FATAL EXCEPTION: main
Process: com.keylesspalace.tusky, PID: 32098
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at java.util.Collections.sort(Collections.java:237)
	at com.keylesspalace.tusky.ak.onResponse(SourceFile:316)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(SourceFile:70)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

* * * *
- Tusky Version: 4.0 (F-Droid)
- Android Version: 7.1.2 (Lineage 14.1)
- Android Device:
- Mastodon instance (if applicable): mastodon.club

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This has been already been fixed here https://github.com/tuskyapp/Tusky/commit/f185c9d379858ac4d6656a5e23681fe9a0b533c0 and will be in the next release

(it crashes because mastodon.club is on a very old Mastodon version)
